on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        CI=false npm install
        CI=false npm run build --if-present
      working-directory: ${{env.working-directory}}

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: cherrybookshop-front
        slot-name: Production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7213238a4e3b4008b6f3139d434b325f }}
        package: .
